### ISSUE TITLE
Global/default door sounds doesn't take effect

### ISSUE THREAD

**Issue by JimmiWazEre** [EndlesNights/ambientdoors#10]
Hi,

I've noticed that whilst applying sounds to doors individually works a treat, applying them globally via module settings does not seem to have any impact.

Is this a bug, or am I doing something wrong?

I'm on Foundry 0.7.9

**Comment by EndlesNights** [comment]
You're right it is a bug, I made a slight error when I changed how defaults were set last patch. Should be fixed. Instead of the values from the function being set, it was trying to pass the entire function, Wooops.

**Comment by JimmiWazEre** [comment]
Hi,

Thanks for picking this up so quickly! Sadly after updating the module to 2.2.2 the global door still do not work.

Attached my global settings just to confirm I'm not doing anything silly.

![image](https://user-images.githubusercontent.com/76654163/103208502-b1fa6b00-48f8-11eb-93a5-55b63cada741.png)

**Comment by EndlesNights** [comment]
You're address might be wrong, remove the word Data unless your files are being stored in the pathway ...\AppData\Local\FoundryVTT\Data\Data\audio\..

**Comment by JimmiWazEre** [comment]
> You're address might be wrong, remove the word Data unless your files are being stored in the pathway ...\AppData\Local\FoundryVTT\Data\Data\audio..

Excellent work, that fixed it 👍

**Comment by EndlesNights** [comment]
Great! Have a nice one.
